baseurl = "https://joshuacasey.net"
title = "Joshua Casey - Autistic Activist"
description = "Joshua is an autistic activist that enjoys video games and is passionate about human rights, free speech, privacy, autistic rights, sex worker rights, the climate change, criminal legal system reform, and child sexual abuse prevention."
theme = "hugo-theme-nix"
languageCode = "en-us"
#disqusShortname = "your_disqus_shortname"
enableRobotsTXT = false
enableEmoji = true
enableGitInfo = true
buildDrafts = false
buildFuture = false

[menu]
  [[menu.header]]
    identifier = "post"
    name = "blog"
    weight = 1
    url = "post/"
  [[menu.header]]
    parent = "post"
    name = "posts"
    url = "/posts"
  [[menu.header]]
    parent = "post"
    name = "tags"
    url = "/tags"
  [[menu.header]]
    name = "contact"
    weight = 2
    url = "/contact"
  [[menu.header]]
    name = "donate"
    weight = 3
    url = "/donate"
 

[params]
  CvURL = "https://resume.joshuacasey.net"
  TwitterID = "AutisticJoshua"
  InstagramID = "JoshuaACasey"
  MastodonURL = "https://qoto.org/@JoshuaACasey"
  TelegramID = "JoshuaACasey"
  Email = "joshua@joshuacasey.net"
  PayPalMeID = "JoshuaACasey"
  GithubID = "JoshuaACasey"
  GitlabId = "JoshuaACasey"
  LinkedInID = "joshuaacasey"
  RedditID = "JoshuaACasey"
  GnuPGFingerprint = "946CFE6B256EE8EA37A3A7262E23A333ECAE0E6B"

  Name = "Joshua Casey"
  HeaderUsername = "joshua"
  HeaderHostname = "joshuacasey.net"
  About = "Joshua is an introverted autistic person that enjoys video games and is passionate about advocating for human rights, free speech, privacy rights, autistic rights, sex worker rights, climate change, criminal legal system reform, and child sexual abuse prevention."
  ProfilePicture = "/profilepic.jpg"
  Favicon = "/favicon.ico"

[sitemap]
 changefreq = "weekly"
 filename = "sitemap.xml"
 priority = 0.5

 [permalinks]
  posts = "/posts/:year/:monthname/:slug/"