baseurl = "https://joshuacasey.net"
title = "Joshua Casey - Autistic Activist"
description = "Joshua is an autistic activist that enjoys video games and is passionate about human rights, free speech, privacy, autistic rights, sex worker rights, the climate change, criminal legal system reform, and child sexual abuse prevention."
theme = "hugo-theme-nix"
languageCode = "en-us"
#disqusShortname = "your_disqus_shortname"
enableRobotsTXT = false
enableEmoji = true
enableGitInfo = true
buildDrafts = false
buildFuture = false

[menu]
  [[menu.header]]
    identifier = "post"
    name = "blog"
    weight = 1
    url = "/posts"
  [[menu.header]]
    parent = "post"
    name = "posts"
    url = "/posts"
  #[[menu.header]]
  #  parent = "post"
  #  name = "tags"
  #  url = "/tags"
  [[menu.header]]
    name = "contact"
    weight = 2
    url = "/contact"
  [[menu.header]]
    name = "donate"
    weight = 3
    url = "/donate"
 

[params]
  CvURL = "https://resume.joshuacasey.net"
  Email = "joshua@joshuacasey.net"
  #FacebookID = ""
  GithubID = "JoshuaACasey"
  GitlabId = "JoshuaACasey"
  #GnuPGFingerprint = ""
  #GoogleAnalytics = ""
  #InstagramID = "JoshuaACasey"
  LinkedInID = "joshuaacasey"
  MastodonURL = "https://qoto.org/@JoshuaACasey"
  #Mobile = ""
  PayPalMeID = "https://paypal.me/JoshuaACasey"
  #Phone = ""
  RedditID = "JoshuaACasey"
  #SlackURL = ""
  #SpotifyID = ""
  #StackExchangeID = ""
  #StackOverflowID = ""
  TelegramID = "JoshuaACasey"
  TwitterID = "AutisticJoshua"
  
    
  Name = "Joshua Casey"
  HeaderUsername = "joshua"
  HeaderHostname = "joshuacasey.net"
  About = "I'm an introverted autistic person that enjoys video games and passionate about advocating for human rights, free speech, privacy, anti-censorship, autistic people's rights, sex worker's rights, climate change, criminal legal system reform, and child sexual abuse prevention. In December 2021, I became a Social Media Manager for Prostasia Foundation, a child protection and human rights organization."
  ProfilePicture = "/profilepic.jpg"
  Favicon = "/favicon.ico"

[sitemap]
 changefreq = "weekly"
 filename = "sitemap.xml"
 priority = 0.5

 [permalinks]
  posts = "/posts/:year/:monthname/:slug/"